// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // 自动模式：docs 目录下所有 _category_*.json 自动归类
  // 其余按字母顺序生成侧边栏
  docsSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

module.exports = sidebars;
